

name: Deploy ARM Template

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (e.g., dev, prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Azure CLI
          uses: azure/setup-azurecli@v1
          with:
            version: '2.33.0'  # Specify the Azure CLI version (latest recommended)

        - name: Azure login using service principal
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

        - name: Deploy ARM Template
          uses: azure/arm-deploy@v1
          with:
            resource-group: 'my-resource-group-${{ github.event.inputs.environment }}'  # Resource group based on environment
            template: './templates/azuredeploy-${{ github.event.inputs.environment }}.json'  # Template file
            parameters: './templates/azuredeploy-${{ github.event.inputs.environment }}-parameters.json'  # Parameter file
            deployment-mode: 'Incremental'  # Set deployment mode (e.g., Incremental or Complete)
  
