

name: Build and Deploy Azure Function

# on:
#   pull_request:
#     branches:
#       - main
#       - dev

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (e.g., dev, prod)'
        required: true
        default: 'refs/heads/main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Prod for env name if on branch main
        if: ${{ github.event.inputs.environment == 'refs/heads/main' }}
        run: echo "Setting environment name ${{github.ref}} "
        env:
          environmentName: "Prod"

      - name: Set Dev for env name if on branch Dev
        if: ${{ github.event.inputs.environment == 'refs/heads/development' }}
        run: echo "Setting environment name ${{github.ref}}"
        env:
          ENV_NAME: "Prod"

      - name: Run Bash script
        run: |
            pwd
            cd ./CICD
            ls -l
            echo "Environment set to: $ENV_NAME"


# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Set up .NET SDK (version 8)
#       - name: Set up .NET SDK
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: '8.x'

#       # Restore dependencies
#       - name: Restore dependencies
#         run: dotnet restore

#       # Build the application
#       - name: Build the application
#         run: dotnet build --configuration Release

#       # Publish the application (produces the artifacts in a folder)
#       - name: Publish the application
#         run: dotnet publish --configuration Release --output ./publish

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment: production

#     steps:
#       # Checkout code again (needed in the deploy job)
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Azure login action to authenticate with Azure
#       - name: Azure Login
#         uses: azure/login@v2
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Deploy ARM Template
#         uses: azure/arm-deploy@v1
#         with:
#           resource-group: ''  # Resource group based on environment
#           template: ''  # Template file
#           parameters: ''  # Parameter file
#           deployment-mode: 'Incremental'  # Set deployment mode (e.g., Incremental or Complete)
  

#       # Deploy to Azure Function App
#       - name: Deploy to Azure Function App
#         uses: azure/functions-action@v1
#         with:
#           app-name: BacktestApi-dev    # Replace with your Azure Function App name
#           package: ./publish                 # Path to the published output folder


